# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.30.2
_src_path: gh:seedcase-project/template-website
for_seedcase: true
github_repo: seedcase-website
github_user: seedcase-project
hosting_provider: netlify
website_format: website
