[files]
extend-exclude = [
  "*.css",
  ".quarto/*",
  "_site/*",
  "*.svg",
  "*nnf-application.html"
]

[default.extend-words]
TRE = "TRE" # trusted research environment
SME = "SME" # small and medium-sized enterprises
