project:
  type: seedcase-theme

website:
  site-url: "https://seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/seedcase-website"
  favicon: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
  navbar:
    logo: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/navbar.svg"
    logo-alt: "Seedcase Project logo: Main page"
    pinned: true
    left:
      - roadmap/index.qmd
      - text: "About"
        href: about/index.qmd
      - text: "Community"
        href: https://community.seedcase-project.org
      - text: "Design"
        href: https://design.seedcase-project.org
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-website"
        aria-label: "GitHub icon: Source repository"
  sidebar:
    - id: about
      title: "About"
      pinned: true
      style: "floating"
      align: left
      collapse-level: 1
      contents:
      - about/index.qmd
      - text: "History"
        href: about/history/index.qmd

bibliography: "includes/references.bib"

format:
  seedcase-theme-html:
    theme:
      - brand
      - custom-styles.scss
    include-before-body:
      - "includes/site-counter.html"
