---
title: System context and scope
order: 3
---

{{< include /includes/_wip.qmd >}}

This document is an overview of the different connections, both human
and computer, with a Data Resource managed by Seedcase.

![C4 Context diagram showing users and external systems that connect to
the Data Resource managed by Seedcase.](/design/images/context.png)

<!-- ## User and organizational -->

The four users and their associated use cases are:

1.  **Users inputting data** into the Data Resource, e.g., authorized
    centers and researchers. The use cases are:
    1.  Authorized centers (GPs and hospitals) upload standardized and
        routine data through the data entry web portal.
    2.  Authorized researchers upload generated data from completed data
        projects. Non-standardized data is either manually processed and
        cleaned before entering into the database or uploaded in its raw
        format and processed with a plugin specific to that data.
2.  **Users requesting access** to a subset of data in the Data
    Resource, e.g., researchers and clinicians. Use cases are:
    1.  Interested researchers browse the catalog of available data and
        the data dictionary.
    2.  Researchers request access to data by submitting a description
        of their proposed data project and selecting the relevant data
        from the catalog. This request is sent to a list of data
        projects to await approval from the data controllers (User 4).
3.  **Users who are administrators and data controllers** of the Data
    Resource, including data managers. Use cases are:
    1.  Approve newly submitted data projects that request data and
        manage existing data projects.
    2.  Approve and authorize researchers to access the web portal for
        data requests and to manage current authorized researchers.
    3.  Manage collection centers' access and authorization.
    4.  Manage or handle potential issues with the data itself, through
        direct access to the data storage.
4.  **External users viewing updates on findings and results** from the
    Data Resource such as aggregate statistics, e.g., policymakers,
    healthcare workers, journalists, researchers, and the general
    public. Use cases are:
    1.  Users view and read through the list of completed, ongoing, and
        proposed data projects that use the Data Resource.
    2.  Users access and view aggregate statistics and the latest
        published findings that are relevant to them/their practice.

There is one (potential) external system involved:

1.  Secure server to transfer requested data for approved data projects.
    This only is necessary when the user who is requesting access is an
    external partner to those who control the Data Resource.

<!-- TODO: Should maybe fill in a technical section, not sure what to add yet. -->
