---
title: "Software architecture documentation"
order: 0
---

{{< include ../../includes/_wip.qmd >}}

## Purpose

The core purpose of writing these architecture documentation is to be
able to describe to ourselves and others what Seedcase is aiming to
accomplish and how it will do that.

We structured the software architecture documentation to follow the
[arc42](https://arc42.org) template and the [C4
Model](https://c4model.com/) as much as is relevant for our situation,
since these both are fairly popular and common templates to use. These
documentation are also continuously evolving documentation as we learn,
test, develop, and grow as a team.

## Reader

The assumed readers are similar to the ones we listed in the [Design of
Seedcase](../index.md) landing page. The complete list of expected
readers is found in the [Stakeholders](introduction.qmd#stakeholders)
section of the Introduction.

## Section overview

1.  [Introduction and goals](introduction.qmd): Targeted to any reader.
    Introduction to the architecture documentation, goals, core
    functionality requirements, guiding principles and philosophies, and
    stakeholders (readers of the documentation).
2.  [Constraints](constraints.qmd): Targeted to any reader. Covers
    barriers or constraints we have self-imposed (for instance, due to
    ideological or philosophical reasons) as well as those we have no
    control over (such as technological server environments that
    Seedcase may be installed on).
3.  [Context and scope](context.qmd): Targeted to any reader. Covers who
    our target or anticipated users are for Seedcase as well as
    potential technological "users" are, for instance, external servers
    connecting to Seedcase.
4.  [Solution strategy](solution-strategy.qmd): Targeted to any reader.
    Describes our proposed solution for the problem we are trying to
    address, as well as which core technologies and architecture designs
    we will use for the solution.
5.  [Building block view](building-block-view.qmd): This is the most
    detailed section. The first part (Level 1) is targeted to readers
    who are more interested in some more technical details while later
    sections are much more highly detailed and written for those with
    much more technical knowledge. We describe the core architecture of
    Seedcase with increasing detail throughout the section, including
    the different parts and connections between parts.
6.  [Runtime view](runtime-view.qmd): Targeted to readers who are
    interested in very technical details. Covers how the different parts
    will actually interact with each other when a user uses Seedcase.
7.  [Deployment view](deployment-view.qmd): Targeted to readers who are
    interested in very technical details.
8.  [Cross-cutting concepts](cross-cutting-concepts.qmd): Targeted to
    both technical and non-technical users. Includes concepts such as
    security, privacy, legal considerations, storage, and dissemination.
9.  [Architecture decisions](architecture-decisions.qmd): Targeted to
    technical readers. Covers the reasons for decisions we make about
    specific technologies or patterns used.
10. [Quality requirements](quality-requirements.qmd): Targeted to any
    reader. This section goes into more detail on the quality goals
    listed in the [introduction](introduction.qmd#quality-goals)
    section.
11. [Risks and technical debt](risks.qmd): Targeted to more technical
    readers, but includes content for non-technical readers. Describes
    potential risks with our solution, such as security risks.

<!-- 12. [Glossary]() -->
