%%{init: {"theme": "neutral", "themeCSS": ".grid .tick {stroke: lightgrey; opacity: 0.2;}"}}%%
gantt
    dateFormat YYYY-MM-DD
    # title
    todayMarker on
    axisFormat %Y-%m

    section Start up
    Searching for and hiring skilled personnel: pre_hire_staff, 2022-01-01, 32w

    section Lifecycle
    Continual assessing security: lifecycle_security, after docs_sw_arch, 156w
    Continual editing and adding to docs: lifecycle_docs, after docs_sw_arch, 156w
    Continual refining of UI: lifecycle_ui, after frontend_data_upload, 156w
    Continual testing of code: lifecycle_testing, after frontend_data_upload, 156w

    section Documentation
    Docs on maintenance and contribution: docs_contributing, after pre_hire_staff, 156w
    Docs on using API and user-facing code: docs_usage, after docs_sw_arch, 156w
    Design docs on software architecture: docs_sw_arch, after pre_hire_staff, 42w
    Design docs sent for review: milestone, review_swc_design, after docs_sw_arch, 0w
    Design docs on data architecture: docs_data_arch, after docs_sw_arch, 32w
    Design docs sent for review: milestone, review_design_docs, after docs_data_arch, 0w

    section Data entry user
    API for CRUD processes on data: api_data_upload, after docs_sw_arch, 16w
    Trigger to update changelog and version data: api_trigger_update_changelog, after api_data_upload, 4w
    Backend structure for changelog metadata: backend_changelog, after api_trigger_update_changelog, 4w
    Backend structure for database: backend_database, after api_trigger_update_changelog, 8w
    Backend structure for version control: backend_dvc, after backend_changelog backend_database, 4w
    Frontend UI for uploading data: frontend_data_upload, after backend_database, 8w
    MVP of data upload: milestone, mvp_data_upload, after frontend_data_upload, 0w
    Start code review: milestone, review_data_upload, after mvp_data_upload, 0w

    section Admin user
    API to authenticate users: api_auth_users, after docs_sw_arch, 6w
    API to register (CRUD) users: api_register_users, after docs_sw_arch, 6w
    Backend structure for user metadata: backend_users, after api_register_users, 6w
    Admin frontend UI for listing users: frontend_admin_researchers_list, after backend_users, 4w
    Trigger for approving data projects: api_trigger_authorization_projects, after backend_projects, 8w
    Start code review: milestone, review_approve_projects, after api_trigger_authorization_projects, 0w
    Admin frontend UI for listing data projects: frontend_admin_projects_list, after mvp_projects, 4w

    section Data discovery user
    API for CRUD processes on (meta)data catalog: api_data_catalog, after mvp_data_upload, 6w
    Backend structure for (meta)data catalog: backend_data_catalog, after api_data_catalog, 6w
    Frontend UI for data catalog: frontend_data_catalog, after backend_data_catalog, 6w
    MVP of data catalog: milestone, mvp_data_catalog, after frontend_data_catalog, 0w

    API for CRUD processes on data projects: api_projects, after api_data_catalog, 6w
    Backend structure for data projects: backend_projects, after api_projects, 6w
    Frontend UI for submitting data project requests: frontend_projects_request_form, after backend_projects, 4w
    MVP of data projects: milestone, mvp_projects, after backend_projects, 0w

    API to select and request data: api_data_request, after api_data_catalog api_projects, 12w
    Trigger to extract requested data: trigger_data_extract, after api_data_request, 12w
    Trigger to transfer data: trigger_data_transfer, after trigger_data_extract, 12w
    Frontend UI for selecting and requesting data: frontend_data_request, after trigger_data_extract, 8w
    MVP of data request and transfer: milestone, mvp_data_request, after frontend_data_request, 0w
    Start code review: milestone, review_data_request, after mvp_data_request, 0w

    section Public user
    Trigger to list info on data projects: api_trigger_format_projects, after mvp_projects, 6w
    Trigger to list changelog: api_trigger_format_changelog, after backend_changelog api_trigger_format_projects, 4w
    Trigger to list/graph summary statistics: api_trigger_format_statistics, after backend_database api_trigger_format_projects, 4w
    Frontend UI for list of projects: frontend_projects, after api_trigger_format_projects, 3w
    Frontend UI for changelog: frontend_changelog, after api_trigger_format_changelog, 3w
    Frontend UI for summary statistic: frontend_statistics, after api_trigger_format_statistics, 3w
    MVP for public facing details: milestone, mvp_projects_list, after frontend_projects frontend_changelog frontend_statistics, 0w

    section Training
    Training docs on deployment/installation: docs_deploy_framework, after mvp_data_upload, 74w
    Training docs on using/customizing Seedcase: docs_customize_framework, after mvp_data_upload, 74w
    Training docs on general data engineer: docs_data_eng, after mvp_data_request, 74w
    Running workshops on using Seedcase: workshops_seedcase, after docs_deploy_framework, 74w

    section Apply to DD2
    Survey and map out all DD2 data: dd2_survey_all_files, after mvp_data_upload, 24w
    Identify all data input sources: dd2_survey_data_inputs, after mvp_data_upload, 24w
    Pre-process and input DD2 data into Seedcase: dd2_input_data, after dd2_survey_data_inputs, 24w
    Build any needed custom processing software: dd2_processing_software, after dd2_input_data, 24w
    MVP for Seedcase instance of DD2 data: milestone, dd2_deployed, after dd2_processing_software, 4w

    section Next steps
    Replicating in ADDITION cohort: next_replic_addition, after dd2_deployed, 24w
