''
'' A PlantUML theme for Seedcase diagrams with Seedcase specific colours
'' based on the C4 green theme 
'' https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/themes/puml-theme-C4_green.puml
''

!$THEME = "seedcase"

' Theme colours

!$WHITE ?= "#FFFFFF"
!$BLACK ?= "#000000"

!$DARKEST_GREEN ?= "#196440"
' "#003224"
!$DARK_GREEN ?= "#74CC8F"
!$MEDIUM_GREEN ?= "#48DC76"
'"#69B580"
!$MEDIUM_GREEN ?= "9BDEAF"
'"#69B580"
!$LIGHT_GREEN ?= "#C6F0D3"

!$DARKEST_GREY ?= "#8B8B8B"
!$DARK_GREY ?= "#ADADAD"
!$MEDIUM_GREY ?= "#D6D6D6"
!$LIGHT_GREY ?= "#F2F2F2"

' C4 diagram

!$PERSON_FONT_COLOR ?= $WHITE
!$PERSON_BG_COLOR ?= $DARKEST_GREEN
!$PERSON_BORDER_COLOR ?= $PERSON_BG_COLOR
!$EXTERNAL_PERSON_FONT_COLOR ?= $PERSON_FONT_COLOR
!$EXTERNAL_PERSON_BG_COLOR ?= $DARKEST_GREY
!$EXTERNAL_PERSON_BORDER_COLOR ?= $EXTERNAL_PERSON_BG_COLOR

!$SYSTEM_FONT_COLOR ?= $BLACK
!$SYSTEM_BG_COLOR ?= $DARK_GREEN
!$SYSTEM_BORDER_COLOR ?= $SYSTEM_BG_COLOR
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $SYSTEM_FONT_COLOR
!$EXTERNAL_SYSTEM_BG_COLOR ?= $DARK_GREY
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $EXTERNAL_SYSTEM_BG_COLOR

!$CONTAINER_FONT_COLOR ?= $BLACK 
!$CONTAINER_BG_COLOR ?= $MEDIUM_GREEN
!$CONTAINER_BORDER_COLOR ?= $DARKEST_GREEN
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $CONTAINER_FONT_COLOR
!$EXTERNAL_CONTAINER_BG_COLOR ?= $MEDIUM_GREY
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= $DARK_GREY

!$COMPONENT_FONT_COLOR ?= $BLACK
!$COMPONENT_BG_COLOR ?= $LIGHT_GREEN
!$COMPONENT_BORDER_COLOR ?= $MEDIUM_GREEN 
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $COMPONENT_FONT_COLOR
!$EXTERNAL_COMPONENT_BG_COLOR ?= $LIGHT_GREY 
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= $MEDIUM_GREY

!$BOUNDARY_BG_COLOR ?= "transparent"
!$BOUNDARY_COLOR ?= $BLACK
!$ARROW_COLOR ?= $BLACK

' Font
skinparam DefaultFontSize 14

'Sequence diagram

skinparam Sequence {
  ArrowColor $ARROW_COLOR
  LifeLineBorderColor $ARROW_COLOR
  LifeLineBackgroundColor $LIGHT_GREY
  ParticipantBackgroundColor $LIGHT_GREY
  ActorBackgroundColor $LIGHT_GREY
}

' State diagram

skinparam State {
  FontSize 18
  FontColor $BLACK
  BorderColor $BLACK
  BackgroundColor $LIGHT_GREY
}
