%% https://kroki.io/ look into more
flowchart TB
  %% Data flow through UI
  data_batch_sample_analysis_raw[] %% Save as file to be processed with specific analysis processing?
  data_batch_questionnaires_raw[]

  data_stream_questionnaires[]

  --> ui_data_input_file[]

  %% Data flow directly through API
  data_routine_redirect[]

  data --> api_post_data_[]
  data --> api_post_data_[]

  %% Flow from API to backend

  ui_data_input_file --> api_post_data_file

  %% Orchestration for backend management
  %% See: https://airflow.apache.org/docs/apache-airflow/stable/index.html
  %% - Trigger to run processing when new raw data is stored
  %% -


  %% QC: Feedback to user
  qc_results --> ui_qc_report
  qc_temp_tbl -->

flowchart TB
  %% Batch input of sample analysis data in its raw form
  data_batch_sample_analysis_raw --> ui_upload_sample_analysis_raw --> api_post_data_raw --> path_sample_analysis_raw --> api_process_sample_analysis_data --> api_add_data_to_database --> path_database

  api_post_data_raw --> api_append_changelog --> path_data_raw_changelog

  api_process_sample_analysis_data --> api_qc_results_sample_analysis --> path_qc_results_sample_analysis --> ui_qc_report_sample_analysis

  api_qc_results_sample_analysis --> api_append_qc_changelog --> path_qc_changelog

  metadata_batch_sample_analysis_raw --> api_post_metadata_raw --> path_metadata_raw

  api_process_sample_analysis_data --> api_extract_metadata_sample_analysis_processed --> path_metadata_processed

