@startuml
node "Seedcase Docker Framework" {
 node "Front End" {
  node "User Interface" {
    [Landing page]
    [User Login pages]
    [Project list pages]
    [Project information ages]
    [Data list pages]
    [Data information pages]
    [Upload Data pages]
    [Download Data pages]
    [Data QC process Pages]
 }
}
@enduml
