@startuml c4-component-ui
' Component diagram for the Seedcase product - Backend: File Storage
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(bee, "Back End Environment")
Container(management, "User and Data Management Layer")
Container(auth, "Authentication")

Container_Boundary(ui, "Front End User Interface") {
  Container_Boundary(auth, "Authentication") {
    Component(user_info, "Information on users", "Metadata on registered users of the Data Resource")
  }
  Container_Boundary(web, "Public web interface") {
    Component(page_landing, "Landing page", $descr="Welcome and overview page that directs users to other pages")
    Component(page_login, "Login page", $descr="To give some users access to specific pages in the Data Resource")
    Component(page_projects_list, "List of data projects", $descr="")
    Component(page_projects_details, "Details on each data project", $descr="")
    Component(page_metadata_list, "List of variables in Data Resource", $descr="")
    Component(page_metadata_details, "Details on each variable in Data Resource", $descr="")
  }
  Container_Boundary(web_admin, "Internal web interface") {
    ' Admin
    Component(page_project_admin, "", $descr="")
    Component(page_data_admin, "", $descr="")

    ' Data entry
    Component(page_data_upload, "", $descr="")
    Component(page_data_download, "", $descr="")
    Component(page_data_qc, "", $descr="")

    ' Data request
    Component(page_data_request, "", $descr="")
  }
}

' Logged in users
Rel(page_login, user_info, "Retrieve user permissions")
Rel(page_login, page_data_upload, "Access with data entry permissions")
Rel(page_login, page_data_request, "Access with data request permissions")
Rel(page_login, page_project_admin, "Access with admin permissions")
Rel(page_login, page_data_admin, "Access with admin permissions")

' Accessing back end
Rel(management, bee, "Retrieve metadata")
Rel(bee, management, "Store metadata")
Rel(management, page_projects_list, "Display")
Rel(management, page_projects_details, "Display")
Rel(management, page_metadata_list, "Retrieve and display")
Rel(management, page_metadata_details, "Retrieve and display")


@enduml

  node "User Interface" {
    [Landing page]
    [User Login pages]
    [Project list pages]
    [Project information ages]
    [Data list pages]
    [Data information pages]
    [Upload Data pages]
    [Download Data pages]
    [Data QC process Pages]
 }
