@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user_researcher, "User: Researcher")
Person(user_admin, "User: Admin")

System_Boundary(seedcase, "Seedcase") {
  System(web_framework, "User Interface")
  System(id_management, "User ID Authentication")
  System(api_framework, "API Layer")
  System(backend_database, "Database")
  System(backend_file_storge, "File/Image Storage")

}
System_Ext(external_server, "External secure server")

Rel(user_researcher, web_framework, "request input data, output data, and data analysis")
Rel(user_admin, web_framework, "Create, manage, and update data projects")
Rel(id_management, web_framework, "User Authetication")
Rel(web_framework, id_management, "")
Rel(web_framework, api_framework, "Send user requests using API communication protocals")
Rel(api_framework, backend_database, "database-specific commands")
Rel(api_framework, backend_file_storge, "Request to get, create, update or remove files")
Rel(api_framework, external_server, "Data extract for approved data projects")
@enduml