@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user_data_input, "Data input")
Person(user_data_request, "Data discover and request")
Person(user_admin, "Admin", "Data contrdollers or data managers")

Person_Ext(user_results, "Explore findings and projects")

Lay_Right(user_admin, user_results)

System(ui, "Data Resource structured by Seedcase")
System_Ext(external_server, "External secure server")

Rel(user_data_input, ui, "Uploads data")
Rel(user_data_request, ui, "Find and request data for project")
Rel(user_results, ui, "Explore findings of study")
Rel(user_admin, ui, "Manages issues and requests for data projects")
Rel_Right(ui, external_server, "Data extract for approved data projects")
Rel(user_data_request, external_server, "Access requested data")
@enduml
