@startuml runtime-data-request
skinparam SequenceMessageAlignment center

' Logged in user who is requesting data from a Data Resource.

participant "User" as u
participant "Frontend" as f
participant "API" as api
participant "Backend" as db

alt New data project
  u -> f --: Select variables to request
  u -> f --: Fill in project metadata
else Re-use data project
  u -> f --: Browse and select data project
  u -> f --: Copy project metadata and modify
end


f -> api: Click "Submit"
api -> db  ++: Store request metadata
api -> api: Inform admin
db -> api --++: Application approved
api -> u --: Send information for next steps

@enduml
