@startuml

title : User manually writes a new row to the Data Resource

participant "user" as u
participant "front end" as f
participant "api" as api
participant "db" as db

u -> f ++: login
f -> api ++: send login request
api -> db ++: check user have \ncorrect permissions
return user have correct \npermission
api -> f --: permit show of  \ndata entry UI
f -> u ++: show data entry UI
u -> f --: enter data and click \non Save and Submit
f -> api ++: send entered data \nwith Complete flag
api -> api : validate data
api -> db ++: write data back
db -> db : create record
db -> api --: confirm creation \nof row in table
api -> f --: receive confirmation
f -> u --: display confirmation
@enduml
