@startuml

title: Logged in user who manually writes a new row to the Data Resource.

participant "User" as u
participant "Front end" as f
participant "API" as api
participant "Back end" as db

f -> u ++: Show data entry UI
u -> f --: Enter data,\nsave, and submit
f -> api ++: Send data with\n"Completed" flag
api -> api : Validate data
api -> db ++: Write data back
db -> db : Create record
db -> api --: Confirm created row
api -> f --: Receive confirmation
f -> u --: Display confirmation
@enduml
