@startuml runtime-login-sequence

' Login and authentication sequence of a registered user

participant "User" as u
participant "Front end" as f
participant "API" as api
participant "Back end" as db

u -> f --: Enter login information
f -> api --: Send login request
api -> db ++: Check permissions level
db --> api --: Send permissions level
api --> f --: Show permission-dependent content
@enduml
