---
title: "Values and principles"
---

Any human creation is influenced by our values and perspectives of the
world around us. We can let these values guide us in our work on
Seedcase Project unconsciously and implicitly, without examining,
critiquing, and evaluating them, or we can explicitly and consciously
select, describe, and explain the values we want to be guided by.

We want to be explicit and conscious about what, how, and importantly,
why we are doing what we decide to do. Being explicit will also help
focus our work and (hopefully) make us more efficient and effective.

The values and principles of the Seedcase Project are ever evolving and
we will update and refine them as we learn and grow.

## Values

Specific values:

-   *How* we work is as important as *what* we make or do
-   Work that is visible and open is easier to participate in and
    contribute to
-   High quality code itself is as valuable as working software
-   Working software without documentation is not as useful without
    documentation
-   Inclusive and accessible design make software and documentation more
    usable and impactful
-   Openness and transparency lead to better collaboration and products

## Principles

We follow these specific principles that are influenced by our values.
We will:

-   document as many processes and activities as we are able to by
    following a [documentation-first
    approach](https://community.seedcase-project.org/guides/documentation-first)
-   work and communicate openly (though privately where necessary)
-   use open licenses for all our outputs
-   design documentation, training material, and software with
    non-technical people in mind
-   incorporate accessibility and inclusive design in both our software
    and documentation outputs
-   use established standards and practices where possible and as
    appropriate
-   follow FAIR principles for
    [data](https://www.go-fair.org/fair-principles/) and
    [software](https://fair-software.nl/)
-   use modern, newer tools even when they aren't widely used, as long
    as there is a strong rationale
-   develop our outputs for health research, but aim for it to be usable
    and useful for other domains as well
