---
title: "Constraints"
---

This document lists technical, political/organizational, and
convention-based constraints that we must consider when developing
Seedcase.

The main "philosophical" and value-based constraints are described in
the [Guiding Principles](/design/introduction.qmd#guiding-principles)
section. These form the basis for all other decisions and designs. Some
of those constraints are summarized below.

## Technical constraints

| Constraints                                        | Background/Motivation                                                            |
|----------------------------------------------------|----------------------------------------------------------------------------------|
| Run on Windows, MacOS, and Linux                   | Our potential users work on any of these systems, so need to design for that     |
| Use open source software dependencies              | We will use an open license, so need to use components that are open as well     |
| Use software that's (relatively) familiar to many  | We want others to contribute, so need to use tools others (likely) know          |
| Integrate GDPR, privacy, and security compliance   | Our target users work with health data, so this is vital to consider             |
| Deployable to servers and locally                  | Could be used locally but mainly used on a server environment                    |
| Storage and computing maybe be different locations | Where data are stored vs analyzed will likely be different, see subsection below |

: Technical constraints we need to consider for Seedcase.

### Computational and storage locations

Considering that Seedcase aim is to simplify structuring and working
with data, we need to clarify and consider that the locations where data
stored and where data is analyzed may be different. These are the
possible combinations described in @tbl-data-analysis-locations.

| Storage | Analysis         |
|---------|------------------|
| Server  | Same server      |
| Server  | Different server |
| Server  | Local            |
| Local   | Local            |
| Local   | Server           |

: Potential combinations where data is stored vs where analysis is done.
'Local' would be the computer itself, while 'server' is an external set
of computers (online or connected internally).
{#tbl-data-analysis-locations}

If the data owners are the same people as the data analysts (for
instance, within a research group), the data and analysis location could
be the same. If the data analysts are external to the owners, the
locations will likely be different. The consequences of these different
combinations is that we need to design Seedcase to be flexible to these
scenarios.

## Organizational constraints

| Constraints                     | Background/Motivation                                                                                   |
|---------------------------------|---------------------------------------------------------------------------------------------------------|
| Time schedule                   | Funding is until end of \~2027                                                                          |
| Resources                       | Currently only have a fixed set of funds                                                                |
| Small team                      | Only have 4-5 people on team, \~3 who are full-time                                                     |
| Limited knowledge/skill support | Data/software engineering is not common in research environments, so local knowledge/skills are limited |

: Organizational constraints we need to consider for Seedcase.

## Political/legal constraints

| Constraints                        | Background/Motivation                                                                       |
|------------------------------------|---------------------------------------------------------------------------------------------|
| Use open source license            | For both practical and philosophical reasons, we will license Seedcase with an open license |
| Need endorsement from legal and IT | They have broad institutional influence, so at least having some support is vital           |

: Political/legal constraints we need to consider for Seedcase.

## Conventions

| Conventions                                      | Background/Motivation                                            |
|--------------------------------------------------|------------------------------------------------------------------|
| Follow standard styling (e.g. PIP3)              | Coding style is vital to readability, so we follow best practice |
| Use [CalVer](https://calver.org/) versioning     | This style is simple and easily shows the age of the software    |
| Incorporate "Test/Doc-Driven Development" styles | Each has pros and cons, we use what works best                   |

: Conventions that we should follow or consider for Seedcase.

