---
title: Community
---

{{< include /includes/_wip.qmd >}}

## Sustainability

A key consideration to Seedcase is ensuring it is sustainable over the
long-term by:

1.  Integrating the development of the framework and using it in
    multiple projects at the host institution Steno Diabetes Center
    Aarhus (SDCA).
2.  Build and document maintenance procedures while prototyping the
    minimum viable product.
3.  Incorporating fundamental open source sustainability concepts and
    documentation such having [Contributing
    Guidelines](contributing/index.qmd) and a [Code of Conduct](contributing/index.qmd#code-of-conduct), as well as encouraging external users to contribute.
4.  Actively contributing back to other open source software that
    Seedcase depends on or that might be used alongside.

## Training and educational development

How widely used Seedcase is or will be depends heavily on the quality of
its documentation and training material. A key concept we will use
throughout development of Seedcase is [Documentation Driven Development](guide-entries/documentation-first/index.html),
where Seedcase's development is guided and informed from the development
of its documentation. Meaning that we will place a high priority on
documentation. We also be creating and running short workshops and
tutorials that teach researchers how they can use Seedcase.
