---
title: Roadmap
format:
  seedcase-theme-html:
    tbl-colwidths: [20, 80]
---

This is a high level roadmap for products we want to create in the Seedcase
Project. We do not include timelines or estimates for completion in this
document. We also often update this roadmap as we progress through the project.

::: callout-tip
For a more detailed and regularly updated roadmap, see our [GitHub
Roadmap](https://github.com/orgs/seedcase-project/projects/22/views/1).
:::

## Product roadmap

This is a non-exhaustive list of products or outputs that we believe can fill
multiple strong needs within the research community. These products, we believe,
have the capacity to substantially improve how research is done. However, given
our current timelines and resources, we can't complete all of them. We list them
here to show our visions and goals.

They are split into three main categories: software and software-related,
technical documentation, and outreach.

Products are listed in the order that we plan to work on and complete them.
Beside each product is one of the following status icons:

  | Status                       | Description                                                                                                                                |
  | :--------------------------: | :----------------------------------------------------------------------------------------------------------------------------------------- |
  |   {{< var status.done >}}    | Products we've completed with a minimally viable product (MVP) that we'll continue to improve and work on                                  |
  |    {{< var status.wip >}}    | Products we are working on currently                                                                                                       |
  |  {{< var status.planned >}}  | Products we plan to complete within the current funding period (end of 2027)                                                               |
  | {{< var status.potential >}} | Products we'd like to work on, but probably won't finish within the current funding period (end of 2027) due to limited time and resources |
  |  {{< var status.ongoing >}}  | Ongoing products without a final release (e.g., not archived or officially published)                                                      |

### Software and software-related

Because software development is an ongoing process, software products are rarely
truly "complete". They continue to evolve through updates and improvements. A
product is considered to have reached MVP and "done" status once its first
version is released on an official software archive (like PyPI for Python
packages).

Some of these products are not strictly software (e.g., templates), but are
designed to work within software environments, integrate with other workflows,
or support research software and data engineering.

::: callout-note
To make our tools easier to get started with for novices and experts alike, we
put a strong emphasis on documentation. Our software and software-related
products generally include documentation on design decisions, usage patterns,
and an API reference.
:::

::: panel-tabset
#### Software

  | Status                     | Software                                                                                                                               |
  | :------------------------: | :------------------------------------------------------------------------------------------------------------------------------------- |
  |  {{< var status.done >}}   | [`seedcase-sprout`](https://github.com/seedcase-project/seedcase-sprout): Grow organised and FAIR data                                 |
  |  {{< var status.done >}}   | [`check-datapackage`](https://github.com/seedcase-project/check-datapackage): Ensure the compliance of your Data Package metadata      |
  |  {{< var status.done >}}   | [`seedcase-flower`](https://github.com/seedcase-project/seedcase-flower): Turn your metadata into human-readable documentation         |
  |   {{< var status.wip >}}   | [`zen-do`](https://github.com/seedcase-project/zen-do): Command line utilities for working with Zenodo                                 |
  |   {{< var status.wip >}}   | [`seedcase-propagate`](https://github.com/seedcase-project/seedcase-propagate): Submit requests for Data Package data                  |
  | {{< var status.ongoing >}} | [`seedcase-soil`](https://github.com/seedcase-project/seedcase-soil): A shared foundation for building Seedcase Python packages        |
  | {{< var status.planned >}} | `seedcase-shears`: Processing raw data into a [Tidy](https://vita.had.co.nz/papers/tidy-data.pdf) [Polars DataFrame](https://pola.rs/) |
  | {{< var status.planned >}} | `seedcase-garden`: Track and manage Data Package requests                                                                              |

  : Status of current and future software products.

#### Software-related products

  | Status                     | Software-related product                                                                                                                                                                                         |
  | :------------------------: | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
  |  {{< var status.done >}}   | [`template-data-package`](https://github.com/seedcase-project/template-data-package): An opinionated template for building Data Packages using Seedcase                                                          |
  |  {{< var status.done >}}   | [`template-python-package`](https://github.com/seedcase-project/template-python-package): An opinionated toolkit for building Python packages                                                                    |
  |  {{< var status.done >}}   | [`template-website`](https://github.com/seedcase-project/template-website): Set up and manage website projects                                                                                                   |
  |  {{< var status.done >}}   | [`t-squared`](https://github.com/seedcase-project/t-squared): Template for building and managing templates                                                                                                       |
  |  {{< var status.done >}}   | [`template-rs`](https://github.com/seedcase-project/template-rs): A Copier template for Rust packages                                                                                                            |
  | {{< var status.ongoing >}} | [`seedcase-theme`](https://github.com/seedcase-project/seedcase-theme): Quarto extension that contains shortcodes, embedded extensions, and style theming for Seedcase Project Quarto-based website repositories |
  | {{< var status.ongoing >}} | [`spaid`](https://github.com/seedcase-project/spaid): Commands for managing Seedcase repositories                                                                                                                |

  : Status of current and future software-related products.
:::

### Technical documentation

Following the [diátaxis](https://diataxis.fr/) method, we split documentation
into four types: tutorials, how-to guides, reference, and explanation. Right
now, we don't create any tutorials, so only the other three are listed below. A
brief description of these types are expanded upon in the sections below. These
technical documentation products reach MVP and "done" status when they are
either:

- Uploaded to an archive like Zenodo (to generate a DOI).
- Uploaded to a software archive (like PyPI) if they are within a software
  product's repository and are executable (the code within runs).

Just like with the software products, these documentation products continue to
evolve and improve over time. They are not static. So even though they have a
"done" status, we continue working on them and continuously release updates to
them.

::: panel-tabset
::::: content-hidden
#### Tutorials

Tutorials are learning-oriented documentation that includes workshops, online
tutorials, and learning shorts. These will be developed as [open educational
resources](https://en.wikipedia.org/wiki/Open_educational_resources).

  | Status                       | Learning resource                                                                                               |
  | :--------------------------: | :-------------------------------------------------------------------------------------------------------------- |
  | {{< var status.potential >}} | Workshop: Introduction to building research software using Python as a solo developer in research environments. |
  | {{< var status.potential >}} | Workshop: Iterative project management and development for effective collaboration and work.                    |
  | {{< var status.potential >}} | Workshop: Building research software using Python in a team setting.                                            |

  : "Wishlist" of learning-type documentation products.
:::::

#### How-to guides

How-to guides are goal-oriented documentation that helps the reader get
something specific done. These include how-to guides, usage guides, and user
manuals.

  | Status                 | Guides or manuals                                                                                                                                     |
  | :--------------------: | :---------------------------------------------------------------------------------------------------------------------------------------------------- |
  | {{< var status.wip >}} | [`guidebook`](https://guidebook.seedcase-project.org/): A guidebook for team collaboration on GitHub                                                  |
  | {{< var status.wip >}} | [`data-pkg-guide`](https://data-pkg-guide.seedcase-project.org/): A guide to engineering and developing research data as a FAIR and tidy data package |

  : "Wishlist" of goal-type documentation products.

#### Reference

Reference material is information-oriented documentation that are technical
descriptions of how things work or why things are done a specific way. These
include reference manuals, API documentation, and technical specifications,
design documentation, as well as documentation for how we work together,
decisions made, or any community contributing guidelines we have.

::::: callout-important
Because of the nature of reference documentation, they don't really have a
"done" status nor do they have clearly defined "endpoints", like uploading to an
archive to generate a DOI. For these reasons, these products are usually
classified as "ongoing". If they are part of a software product, they are
considered "done" when the software product is released on an official software
archive (like PyPI for Python packages).
:::::

  | Status                     | Information resource                                                                                                    |
  | :------------------------: | :---------------------------------------------------------------------------------------------------------------------- |
  | {{< var status.ongoing >}} | [`design`](https://github.com/seedcase-project/design): Principles and patterns for development in the Seedcase Project |
  | {{< var status.ongoing >}} | [`team`](https://github.com/seedcase-project/team): Internal docs for onboarding and admin information                  |
  | {{< var status.ongoing >}} | [`seedcase-website`](https://github.com/seedcase-project/seedcase-website): Main website for the Seedcase Project       |

  : "Wishlist" of informational-type documentation products.

#### Explanation

Explanation material is understanding-oriented documentation that focuses on
reflection and broadening knowledge or understanding. These include opinion
pieces, explanations, theoretical or thought-provoking pieces, and outreach
materials.

<!-- TODO: This section needs some work -->

  | Status                     | Deliverable                                                                                                                        |
  | :------------------------: | :--------------------------------------------------------------------------------------------------------------------------------- |
  | {{< var status.ongoing >}} | [`community`](https://github.com/seedcase-project/community): Community building, outreach, and updates on the Seedcase Project    |
  | {{< var status.ongoing >}} | [`decisions`](https://github.com/seedcase-project/decisions): A record of decisions on tools and processes in the Seedcase Project |

  : "Wishlist" of explanation-type documentation products.
:::

### Examples that use our products

These are practical examples of how to use Seedcase software to structure
datasets and prepare them to be used by others. The data is openly licensed.

  | Status                     | Deliverable                                                                                                                                                                                                                                  |
  | :------------------------: | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
  | {{< var status.ongoing >}} | [`example-rhesus-monkeys`](https://github.com/seedcase-project/example-rhesus-monkeys): Example repository for making a data package with data from a study of maternal obesity in rhesus monkeys                                            |
  | {{< var status.ongoing >}} | [`example-seed-beetle`](https://github.com/seedcase-project/example-seed-beetle): Example repository for making a data package with data from a study of complex mitonuclear interactions and metabolic costs of mating in male seed beetles |
  | {{< var status.ongoing >}} | [`example-rainforest`](https://github.com/seedcase-project/example-rainforest): Example repository for making a data package with data from a study of seed germination in the rainforest                                                    |

## Collaborations and users

As we now have working packages, we are currently collaborating with several
other projects to integrate our software and build data packages for their data.
The projects we collaborate with are:

- [DP-Next](https://dp-next.github.io/)
- [ON-LiMiT](https://onlimit.org/)

Other groups have also expressed interest and may become future collaborators.
These other projects are:

- [ADDITION-PRO](https://addition.au.dk/research/addition-dk/addition-pro/)
- [Health in Central Denmark
  Region](https://www.stenoaarhus.dk/forskning/helbred-i-midt/)
- [DARTER](https://steno-aarhus.github.io/darter-project/) (register-based
  research project at Steno)
