flowchart TB
  subgraph 'Data and Metadata'
    data_batch
    metadata_batch
  end

  subgraph UI
    ui_upload_batch
    ui_upload_metadata
  end

  subgraph API
    api_post_metadata
    api_qc_general
    api_post_to_database
    api_qc_specific
    api_append_changelog
  end

  subgraph Backend
    path_database
    path_changelog
    path_metadata
    path_qc_results
    path_changelog
  end

  metadata_batch --> ui_upload_metadata --> api_post_metadata --> path_metadata

  data_batch --> ui_upload_batch --> api_qc_general --> api_post_to_database --> path_database

  api_post_to_database --> api_qc_specific --> path_qc_results

  api_post_to_database --> api_append_changelog --> path_changelog
