name: Build and deploy website

on:
  push:
    branches: main

jobs:
  build-deploy-docs:
    uses: seedcase-project/.github/.github/workflows/deploy-docs.yml@main
    secrets: 
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
